CREATE DATABASE DB_EMPRESA;
USE DB_EMPRESA;

CREATE TABLE FUNCIONARIOS(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    departamento VARCHAR(255) NOT NULL,
    salario FLOAT NOT NULL
);